# Generated by Django 3.2.9 on 2021-11-21 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0006_auto_20211121_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='playlists.playlist'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='parent_order',
            field=models.IntegerField(default=1),
        ),
    ]
