# Generated by Django 3.2.9 on 2021-11-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0008_tvshowproxy_tvshowseasonproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='type',
            field=models.CharField(choices=[('MOV', 'Movie'), ('TVS', 'Tv Show'), ('SEA', 'Season'), ('PLA', 'Playlist')], default='PLA', max_length=3),
        ),
    ]
