# Generated by Django 3.2.9 on 2021-11-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_video_publish_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='publish_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
