# Generated by Django 3.2.9 on 2021-11-22 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_taggeditem_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggeditem',
            name='object_id',
        ),
    ]
